name: Add Bounty to Issue

on:
  issue_comment:
    types: [created]

jobs:
  add-bounty:
    if: contains(github.event.comment.body, '/bounty') && github.event.comment.user.login == 'ngundotra'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - run: pnpm install

      - name: Parse bounty amount
        id: parse-bounty
        run: |
          echo "github.event.comment.body: ${{ github.event.comment.body }}"
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "COMMENT_BODY: $COMMENT_BODY"
          BOUNTY_AMOUNT=$(echo "$COMMENT_BODY" | grep -oE '/bounty\s+0\.001' | sed 's/\/bounty\s\+//')
          echo "bounty_amount=${BOUNTY_AMOUNT//\/bounty/}" >> $GITHUB_OUTPUT

      - name: Create/update bounty file
        run: |
          pnpm ts-node scripts/createOrSetBounty.ts \
            --issue ${{ github.event.issue.number }} \
            --amount ${{ steps.parse-bounty.outputs.bounty_amount }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch-token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: "Add bounty for Issue #${{ github.event.issue.number }}"
          title: "Add bounty for Issue #${{ github.event.issue.number }}"
          body: "Auto-generated PR to add bounty for Issue #${{ github.event.issue.number }}"
          branch: "add-bounty-issue-${{ github.event.issue.number }}"
          labels: "bounty"
          base: main
          maintainer-can-modify: true
          delete-branch: true

      # Merge in PR using gh cli
      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --merge --admin --repo ${{ github.repository }}

      - name: Add bounty label and comment
        uses: actions/github-script@v7
        with:
          script: |
            const { issue } = context.payload;
            // Add bounty label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              labels: [`bounty`]
            });

            // Add comment about bounty PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: `✅ Added bounty of ${process.env.BOUNTY_AMOUNT} SOL in PR #${{ steps.create-pr.outputs.pull-request-number }}`
            });
        env:
          BOUNTY_AMOUNT: ${{ steps.parse-bounty.outputs.bounty_amount }}
