name: Pay Bounty on Merge

on:
  pull_request:
    types: [closed]
    branches: [main, master]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string

jobs:
  run-script:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - run: pnpm install

      # - run: npm run build # If you need to compile TypeScript

      - run: pnpm ts-node scripts/payBounty.ts # Directly run TypeScript
        env:
          SOLANA_PRIVATE_KEY: ${{ secrets.SOLANA_PRIVATE_KEY }}
          SOLANA_RPC_URL: ${{ secrets.SOLANA_RPC_URL }}
          PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr_number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch-token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: "Pay bounty for PR #${{ github.event.pull_request.number || inputs.pr_number }}"
          title: "Pay bounty for PR #${{ github.event.pull_request.number || inputs.pr_number }}"
          body: "Auto-generated PR from daily bounty payment"
          branch: "bounty-payment-pr-${{ github.event.pull_request.number || inputs.pr_number }}"
          labels: "bounty-payment"
          base: main
          maintainer-can-modify: true
          delete-branch: true
