name: Run TypeScript on Merge

on:
  pull_request:
    types: [closed]
    branches: [main, master]

jobs:
  run-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      # - run: npm run build # If you need to compile TypeScript

      - run: npx ts-node scripts/payBounty.ts # Directly run TypeScript
        env:
          SOLANA_PRIVATE_KEY: ${{ secrets.SOLANA_PRIVATE_KEY }}
          SOLANA_RPC_URL: ${{ secrets.SOLANA_RPC_URL }}
          PR_NUMBER: ${{ github.event.number }}
