name: Pay Bounty on Merge

on:
  pull_request:
    types: [closed]
    branches: [main, master]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  run-script:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - run: pnpm install

      - run: pnpm ts-node scripts/payBounty.ts
        env:
          SOLANA_PRIVATE_KEY: ${{ secrets.SOLANA_PRIVATE_KEY }}
          SOLANA_RPC_URL: ${{ secrets.SOLANA_RPC_URL }}
          PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr_number }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch-token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: "Record bounty payment for PR #${{ github.event.pull_request.number || inputs.pr_number }}"
          title: "Record bounty payment for PR #${{ github.event.pull_request.number || inputs.pr_number }}"
          body: "Auto-generated PR to record bounty payment for PR #${{ github.event.pull_request.number || inputs.pr_number }}"
          branch: "bounty-payment-pr-${{ github.event.pull_request.number || inputs.pr_number }}"
          labels: "bounty-payment"
          base: main
          maintainer-can-modify: true
          delete-branch: true

      # Merge in PR using gh cli
      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --merge --admin --repo ${{ github.repository }}
