name: Validate New Chess Games

on:
  pull_request:
    paths:
      - "chess/games/**/*.pgn"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: " "
          files: |
            added: chess/games/**/*.pgn
            modified: chess/games/**/*.pgn

      - name: Check single file modification
        run: |
          added_count=$(echo "${{ steps.changed-files.outputs.added_files }}" | wc -w)
          modified_count=$(echo "${{ steps.changed-files.outputs.modified_files }}" | wc -w)
          total_count=$((added_count + modified_count))

          if [ "$total_count" -gt 1 ]; then
            echo "::error::PRs can only modify 1 game file at a time. Found $total_count files ($added_count added, $modified_count modified)."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install chess.js @types/node

      - name: Validate new games
        run: |
          # Validate new files
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "Validating $file"
            ts-node chess/scripts/checkGameById.ts $(basename $file .pgn | cut -d_ -f2)
            ts-node chess/scripts/validateGames.ts
          done

          # Validate modified files without GameID check
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "Validating modified file $file"
            ts-node chess/scripts/validateGames.ts
          done
